import { DIRS, STRAINS, num, str } from "../core/utils.mjs";
import { actualTricks, canonicalDouble, contractDisplay, scoreNS } from "../bridge/scoring.mjs";

export function normalizeHand(raw,src={}){
  const hands={},dd={};for(const d of DIRS){const p=prefix(d);hands[d]={S:str(raw[`${p}Spades`]),H:str(raw[`${p}Hearts`]),D:str(raw[`${p}Diamonds`]),C:str(raw[`${p}Clubs`]),hcp:num(raw[`${p}Points`])};dd[d]={};for(const s of STRAINS)dd[d][s]=num(raw[`${p}Makeable${s}`]);}
  return {section:raw.section??null,round:num(raw.round),seg:num(raw.seg,0),board:num(raw.board),alias:raw.roundOrSegAlias??null,dealer:str(raw.dealer).toUpperCase(),vulnerability:raw.vulnerable??raw.vulnerableUseBoth??null,hands,doubleDummyTricks:dd,par:{contracts:Array.isArray(raw.parContracts)?raw.parContracts:(raw.parContractsStr?[raw.parContractsStr]:[]),scoreNS:num(raw.totalPointPar)},provenance:{kind:'raw_api',source:src.url??null}};
}
export function normalizeBoardResult(r,hand,src={}){
  const score=scoreNS(r),datum=num(r.datum),decl=str(r.declarer).toUpperCase(),strain=str(r.contractSuit).toUpperCase(),level=num(r.contractTrick),tricks=actualTricks(level,r.result),dd=decl&&strain?hand?.doubleDummyTricks?.[decl]?.[strain]??null:null;
  return {table:num(r.table),room:num(r.room),players:{N:r.northName??'',E:r.eastName??'',S:r.southName??'',W:r.westName??''},members:{N:r.northMember??'',E:r.eastMember??'',S:r.southMember??'',W:r.westMember??''},recordKind:recordKind(r,level,strain),contract:{level,strain,double:canonicalDouble(r.contractDouble),declarer:decl,result:str(r.result)||'=',actualTricks:tricks,display:contractDisplay(r)},scoreNS:score,rawScore:num(r.tp),datumScoreNS:datum,datumDifference:score!=null&&datum!=null?score-datum:null,ximp:num(r.ximp),matchImpNS:num(r.impNS,0),matchImpEW:num(r.impEW,0),ddTricks:dd,tricksVsDD:tricks!=null&&dd!=null?tricks-dd:null,openingLead:{card:r.leadCard??'',rank:r.leadCardRank??'',suit:r.leadCardSuit??''},flags:{doNotDatum:Boolean(r.doNotDatum),fouledVersion:r.fouledVersion??'',phantomNS:Boolean(r.phantomNS),phantomEW:Boolean(r.phantomEW)},provenance:{kind:'raw_api',source:src.url??null}};
}
export function normalizeBoardBundle(raw){const hand=normalizeHand(raw.hand.data,raw.hand.meta);const results=(raw.results.data||[]).map(x=>normalizeBoardResult(x,hand,raw.results.meta));return {meta:raw.meta,hand,results,provenance:{sources:[raw.hand.meta,raw.results.meta]}}}

export function normalizeRoundMeta(x,src={}){return {section:x.section,round:num(x.round),seg:num(x.seg,0),group:x.group??'',lengthMinutes:num(x.length),start:x.start??null,end:x.end??null,note:x.note??'',provenance:{kind:'raw_api',source:src.url??null}}}
export function normalizeRoundTable(x,src={}){return {section:x.section,round:num(x.round),seg:num(x.seg,0),table:num(x.table),room:num(x.room),boardRange:{low:num(x.lowBoard),high:num(x.highBoard),complete:num(x.boardCompleteCount)},nsTeam:{no:num(x.ns),name:x.nsName??'',flag:x.nsFlag??'',imps:num(x.impsNS,0),vp:num(x.vpNS,0),penVp:num(x.penVpNS,0),adjImp:num(x.adjImpNS,0),phantom:Boolean(x.phantomNS)},ewTeam:{no:num(x.ew),name:x.ewName??'',flag:x.ewFlag??'',imps:num(x.impsEW,0),vp:num(x.vpEW,0),penVp:num(x.penVpEW,0),adjImp:num(x.adjImpEW,0),phantom:Boolean(x.phantomEW)},lineup:{N:{name:x.northName??'',member:x.northMember??'',index:num(x.northIndex)},S:{name:x.southName??'',member:x.southMember??'',index:num(x.southIndex)},E:{name:x.eastName??'',member:x.eastMember??'',index:num(x.eastIndex)},W:{name:x.westName??'',member:x.westMember??'',index:num(x.westIndex)}},lineupComplete:Boolean(x.lineUPComplete),hasLineup:Boolean(x.hasLineUP),walkOverKind:num(x.walkOverKind,0),isVG:Boolean(x.isVG),provenance:{kind:'raw_api',source:src.url??null}}}
export function normalizeRoundRank(x,src={}){return {teamNo:num(x.no),teamName:x.name??'',flag:x.flag??'',rank:num(x.rank),totalScore:num(x.totalScore,0),penalty:num(x.pen,0),carryOver:num(x.carryOver,0),provenance:{kind:'raw_api',source:src.url??null}}}
export function normalizeSwissTeam(x,src={}){return {teamNo:num(x.teamNO),teamName:x.teamName??'',flag:x.flag??'',rank:num(x.rank),vps:num(x.vps,0),penalty:num(x.penalty,0),carryOver:num(x.carryOver,0),impQ:num(x.impQ),winCount:num(x.winCount,0),tieCount:num(x.tieCount,0),avgVsVp:num(x.avgVsVp),rounds:(x.rounds||[]).map(r=>({round:num(r.round),teamNo:num(r.no),vsNo:num(r.vsNo),imps:num(r.imps,0),vsImps:num(r.vsImps,0),vp:num(r.vp,0),vsVp:num(r.vsVp,0),bam:num(r.bam,0),vsBam:num(r.vsBAM,0),isWin:Boolean(r.isWin),isBamWin:Boolean(r.isBAMWin)})),provenance:{kind:'raw_api',source:src.url??null}}}
export function normalizeDatumRound(x,src={}){return {round:num(x.round),section:x.section??null,title:x.title??'',subTitle:x.subTitle??'',updatedAt:x.update??null,boards:(x.boards||[]).map(b=>({board:num(b.board),datum:num(b.datum),ximp:num(b.ximp,0)})),players:(x.ximps||[]).map(p=>({memberNo:String(p.no??''),flag:p.flag??'',room:num(p.room),team:p.team??'',teamNo:num(p.teamNO),table:num(p.table),totalXimp:num(p.ximps,0),player:p.player??'',position:p.position??'',boardsXimp:(p.boardsXimp||[]).map(b=>({board:num(b.board),ximp:num(b.ximp),datumField:num(b.datum)}))})),provenance:{kind:'raw_api',source:src.url??null}}}
export function normalizeButler(x,src={}){return {section:x.section??null,title:x.title??'',subTitle:x.subTitle??'',updatedAt:x.update??null,players:(x.butlers||[]).map(p=>({memberNo:String(p.no??''),name:p.name??'',team:p.team??'',flag:p.flag??'',rank:num(p.rank),ximps:num(p.ximps,0),boards:num(p.boards,0),butler:num(p.butler),aob:num(p.aob),correctButler:num(p.correctButler)})),provenance:{kind:'raw_api',source:src.url??null}}}
function prefix(d){return ({N:'north',E:'east',S:'south',W:'west'})[d]}
function recordKind(r,l,s){if(l&&s)return 'played-contract';if(r.fouledVersion)return 'fouled';if(r.doNotDatum)return 'adjusted-or-excluded';if((Number(r.penNS)||0)!==0||(Number(r.penEW)||0)!==0)return 'adjusted';return 'no-contract-or-unknown'}
